dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard_view'),
    path('valida_acao', views.ValidaAcao.as_view(), name='valida_acao'),
]

etapa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.EtapaListView.as_view(), name='etapa_list'),
    path('new/', views.EtapaCreateView.as_view(), name='etapa_new'),
    path('<int:pk>/edit/', views.EtapaUpdateView.as_view(), name='etapa_edit'),
    path('<int:pk>/detail/', views.EtapaDetailView.as_view(), name='etapa_detail'),
    path('<int:pk>/delete/', views.EtapaDeleteView.as_view(), name='etapa_delete'),
    path('acoes/', views.AcaoListView.as_view(), name='acao_list'),
    path('acoes/new/', views.AcaoCreateView.as_view(), name='acao_new'),
    path('acoes/<int:pk>/edit/', views.AcaoUpdateView.as_view(), name='acao_edit'),
    path('acoes/<int:pk>/detail/', views.AcaoDetailView.as_view(), name='acao_detail'),
    path('acoes/<int:pk>/delete/', views.AcaoDeleteView.as_view(), name='acao_delete'),
]

gerpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('naturezas/', include('natureza.urls')),
    path('etapas/', include('etapa.urls')),
    path('processos/', include('processo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

distribuicao/models.py
from django.db import models


class TipoDistribuicao(models.Model):
    nome = models.CharField(
        max_length=70,
        verbose_name='Nome',
        help_text='Nome do tipo de distribuição.',
    )
    descricao = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='Descrição',
        help_text='Descrição do tipo de distribuição.',
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Está ativo?',
        help_text='Indica se o tipo de distribuição está ativo.',
    )

    class Meta:
        ordering = ['nome']
        verbose_name = 'Tipo de Distribuição'
        verbose_name_plural = 'Tipos de Distribuição'

    def __str__(self):
        return str(self.nome)

etapa/models.py
from django.db import models
from django.urls import reverse


class ActiveObjectsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class Etapa(models.Model):
    nome = models.CharField(
        max_length=200,
        verbose_name='Etapa',
        help_text='Nome da etapa.',
    )
    descricao = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='Descrição da etapa',
        help_text='Descreve a função da etapa.',
    )
    ordem = models.PositiveSmallIntegerField(
        null=True,
        unique=True,
        verbose_name='Ordem',
        help_text='Define a posição/ordem da etapa.',
    )
    distribuicao = models.ManyToManyField(
        'distribuicao.TipoDistribuicao',
        db_index=True,
        blank=True,
        db_table='etapa_distribuicao',
        verbose_name='Distribuição',
        help_text='Indica quais tipos de distribuição podem ser usados para essa etapa.'
    )
    vincular_analista = models.BooleanField(
        default=False,
        verbose_name='Vincular analista',
        help_text='Indica se o sistema deve se lembrar do usuário escolhido na primeira distribuição do processo.'
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Está ativa?',
        help_text='Indica se a etapa está ou não ativa.',
    )

    objects = models.Manager()
    active_objects = ActiveObjectsManager()

    class Meta:
        ordering = ['ordem', 'nome']

    def get_absolute_url(self):
        return reverse('etapa_detail', args=[str(self.id)])

    def __str__(self):
        return self.nome

    def __unicode__(self):
        return self.nome


class Acao(models.Model):
    etapa = models.ForeignKey(
        Etapa,
        on_delete=models.CASCADE,
        verbose_name='Etapa',
        help_text='Etapa à qual a ação está vinculada.'
    )
    nome = models.CharField(
        max_length=200,
        verbose_name='Nome',
        help_text='Nome da ação.'
    )
    descricao = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='Descrição',
        help_text='Descrição da ação.',
    )
    etapa_seguinte = models.ForeignKey(
        Etapa,
        related_name='etapa_seguinte',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='Etapa seguinte',
        help_text='Etapa para a qual o processo deve ser movido.',
    )
    finalizar = models.BooleanField(
        default=False,
        verbose_name='Finalizar?',
        help_text='Indica se o protocolo deve ser finalizado ao executar a ação.'
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Está ativa?',
        help_text='Indica se a ação está ou não ativa.',
    )

    objects = models.Manager()
    active_objects = ActiveObjectsManager()

    class Meta:
        ordering = ['nome', 'etapa']
        verbose_name = 'Ação'
        verbose_name_plural = 'Ações'

    def get_absolute_url(self):
        return reverse('etapa_detail', args=[str(self.id)])

    def __str__(self):
        return str(self.nome + " (" + self.etapa.nome + ")")

    def __unicode__(self):
        return str(self.nome + " (" + self.etapa.nome + ")")

natureza/models.py
from django.db import models
from django.urls import reverse


class Natureza(models.Model):
    nome = models.CharField(
        max_length=200,
        verbose_name='Nome da Natureza',
    )
    prazo = models.IntegerField(
        null=True,
        blank=True,
        default=30,
        verbose_name='Prazo legal',
        help_text='Prazo legal da prenotação. Período de validade oficial dos processos ligados à esta natureza.',
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Está ativo?',
        help_text='Indica se a natureza está ou não ativa.',
    )
    pk_import = models.IntegerField(
        unique=True,
        null=True,
        blank=True,
        verbose_name='ID Legado',
        help_text='Indica que o registro foi importado de outro sistema e essa é sua chave primária naquele sistema.',
    )

    class Meta:
        ordering = ['nome']

    def get_absolute_url(self):
        return reverse('natureza_detail', args=[str(self.id)])

    def __str__(self):
        return self.nome

    def __unicode__(self):
        return self.nome

processo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Processo(models.Model):
    l1_protocolo = models.IntegerField(
        unique=True,
        db_index=True,
        verbose_name='Processo',
        help_text='Número do processo/protocolo.'
    )
    natureza = models.ForeignKey(
        'natureza.Natureza',
        on_delete=models.PROTECT,
        verbose_name='Natureza',
        help_text='Natureza do processo.'
    )
    dta_inclusao = models.DateField(
        null=True,
        blank=True,
        verbose_name='Data de entrada',
        help_text='Data em que o processo deu entrada (inclusão).'
    )
    dta_entrega = models.DateField(
        null=True,
        blank=True,
        verbose_name='Previsão de entrega',
        help_text='Data da previsão de entrega do processo à parte.'
    )
    dta_prazo = models.DateField(
        null=True,
        blank=True,
        verbose_name='Vencimento',
        help_text='Data em que vence o prazo legal do processo.'
    )
    etapa = models.ForeignKey(
        'etapa.Etapa',
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name='Etapa',
        help_text='Etapa do processo.'
    )
    parte = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='Parte',
        help_text='Nome/identificação da parte/cliente.'
    )
    atendente = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='Atendente',
        help_text='Nome/identificação do funcionário que deu entrada(incluiu) no processo.'
    )
    agente = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Agente',
        help_text='Nome/identificação do funcionário responsável pelo processo na presente etapa.'
    )
    vinculo = models.UUIDField(
        null=True,
        blank=True,
        verbose_name='Vínculo',
        help_text='Indica o vículo existente entre este e outros procesos.',
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Está ativo?',
        help_text='Indica se o processo está ativo.'
    )

    class Meta:
        ordering = ['l1_protocolo']

    def get_absolute_url(self):
        return reverse('processo_detail', args=[str(self.id)])

    def __str__(self):
        return str(self.l1_protocolo)


class ProcessoAnalistaEtapa(models.Model):
    l1_protocolo = models.ForeignKey(
        Processo,
        on_delete=models.CASCADE,
        verbose_name='Processo',
        help_text='Número do processo/protocolo.'
    )
    etapa = models.ForeignKey(
        'etapa.Etapa',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Etapa',
        help_text='Etapa do processo.'
    )
    analista = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Analista',
        help_text='Nome/identificação do funcionário responsável pela análise do processo.'
    )

    class Meta:
        ordering = ['l1_protocolo']
        unique_together = ('l1_protocolo', 'etapa')
        verbose_name = 'Analista do Processo na Etapa'
        verbose_name_plural = 'Analistas dos Processos por Etapa'

    def __str__(self):
        return "[ " + str(self.l1_protocolo) + " - " + str(self.etapa) + " ] " + str(self.analista)

processo/forms.py
from django import forms
from .models import Processo


class ProcessoChangeForm(forms.ModelForm):
    class Meta:
        model = Processo
        fields = (
            'l1_protocolo',
            'dta_inclusao',
            'dta_prazo',
            'natureza',
            'etapa',
            'parte',
            'atendente',
            'agente',
        )
    l1_protocolo = forms.IntegerField(
        disabled=True,
        label='Processo',
        help_text='Número do processo/protocolo.',
    )
    dta_inclusao = forms.DateField(
        disabled=True,
        label='Data de entrada',
        help_text='Data em que o processo deu entrada (inclusão).'
    )
    dta_prazo = forms.DateField(
        disabled=True,
        label='Vencimento',
        help_text='Data em que vence o prazo legal do processo.'
    )
    parte = forms.CharField(
        disabled=True,
        label='Parte',
        help_text='Nome/identificação da parte/cliente.',
    )
    atendente = forms.CharField(
        disabled=True,
        label='Atendente',
        help_text='Nome/identificação do funcionário que deu entrada(incluiu) no processo.',
    )
    agente = forms.CharField(
        disabled=True,
        label='Agente',
        help_text='Nome/identificação do funcionário responsável pelo processo na presente etapa.',
    )

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views import View
from etapa.models import Etapa, Acao
from accounts.models import ProjectUser
from processo.models import Processo
from django.http import JsonResponse


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard_view.html'

    def get_user_etapas(self):
        userid = self.request.user.id
        return ProjectUser.objects.get(id=userid).get_etapas()

    def get_user_etapa_acoes(self):
        etapasid = self.get_user_etapas().values_list('groups__projectgroup__etapas__id', flat=True)
        return Etapa.objects.filter(
            is_active=True,
            id__in=etapasid,
            acao__is_active=True,
        ).values(
            'acao__id',
            'acao__etapa',
            'acao__nome',
            'acao__descricao',
            'acao__etapa_seguinte',
            'acao__finalizar',
            'acao__is_active',
        ).distinct().order_by('acao__nome',)

    def get_user_processos(self):
        userid = self.request.user.id
        return ProjectUser.objects.get(id=userid).get_processos()


class ValidaAcao(LoginRequiredMixin, View):

    def get_etapa_seg_dists(self, acao):
        etapa_seguinte_distribuicoes = []

        if len(acao) > 0:
            count = 0
            while (count < len(acao)):
                if acao[count]['etapa_seguinte__distribuicao']:
                    etapa_seguinte_distribuicoes.append(acao[count]['etapa_seguinte__distribuicao'])
                count = count + 1

        return etapa_seguinte_distribuicoes

    def get_ana_listas(self, processo_id, acao):
        processo = Processo.objects.get(id=processo_id)
        etapa_seguinte_distribuicoes = self.get_etapa_seg_dists(acao)
        ana_lista_qtd = ProjectUser.get_analistas_proc_count()

        ana_lista = list(ProjectUser.objects.filter(
            receber_distribs__in=etapa_seguinte_distribuicoes,
            receber_procs=True,
            naturezas=processo.natureza
        ).exclude(id=self.request.user.id).values('username', 'id').distinct())

        count_al = 0
        while (count_al < len(ana_lista)):
            count_al_qtd = 0
            ana_lista[count_al]['proc_qtd'] = 0
            while (count_al_qtd < len(ana_lista_qtd)):
                if ana_lista[count_al]['id'] == ana_lista_qtd[count_al_qtd].id:
                    ana_lista[count_al]['proc_qtd'] = ana_lista_qtd[count_al_qtd].proc_qtd
                count_al_qtd = count_al_qtd + 1
            count_al = count_al + 1

        return list(ana_lista)

    def get(self, request):
        acao = Acao.objects.filter(
            id=self.request.GET['acao']
        ).values('id', 'etapa', 'etapa_seguinte', 'etapa_seguinte__nome', 'etapa_seguinte__distribuicao', 'finalizar')
        analista = self.request.GET['analista']
        #usuario = ProjectUser.objects.get(id=self.request.user.id).username

        """A ação executada sempre retornará 2 valores 3 um terceiro valor opcional.
        Os dois valores são o id da ação, de onde identifica-se a etapa e etapa_seguinte, e o protocolo.
        De posse desses dois parâmetos a view retorna valores para o template. Esses valores podem ser
        a confirmação da execução da ação ou a lista de analistas elegíveis no caso em que se perceba a
        necessidade de distribuição.

        Uma vez enviada a lista de analistas, parte do template responder com um analista selecionado.
        Nesse caso, o terceiro valor (analista) é informado, e esta view executa a distribuição e informa
        o template."""

        etapa_seguinte_distribuicoes = self.get_etapa_seg_dists(acao)

        """Já com a lista de distribuições da etapa seguinte, não sendo informado o analista selecionado para a
        distribuição, cria-se uma lista de analistas elegíveis para a distribuição."""
        if len(etapa_seguinte_distribuicoes) > 0 and len(analista) < 1:
            analistas_selecao = self.get_ana_listas(self.request.GET['processo'], acao)
        else:
            analistas_selecao = None

        """No caso do analista ser informado, o sistema executa a distribuição."""
        if len(analista) == 1 and len(etapa_seguinte_distribuicoes) > 0:
            proc_distrib = list(ProjectUser.objects.filter(id=analista,).values('username', 'id').distinct())
        else:
            proc_distrib = None

        """Retorna as variáveis ao template, que as tratará de acordo com os requisitos do negócio."""
        return JsonResponse(
            {
                "analistas": analistas_selecao,
                "proc_etapa": acao[0]['etapa_seguinte__nome'],
                "proc_active": not acao[0]['finalizar'],
                "proc_distrib": proc_distrib,
            }
        )

distribuicao/views.py
from django.shortcuts import render

# Create your views here.

templates/acao_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Ações - Nova{% endblock title %}

{% block content %}
        <h3>Ações</h3>
        <span class="text-muted">Cadastrar ação</span>
        <br /><br />
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'acao_list' %}" class="btn btn-outline-secondary ml-2" rule="button">Voltar para lista</a>
            <input type="submit" class="btn btn-outline-success ml-2" value="Salvar">
        </form>

{% endblock content %}

templates/etapa_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Etapas - Detalhes{% endblock title %}

{% block content %}
        <h3>Etapas</h3>
        <span class="text-muted">Detalhes da etapa: <b>{{ etapa.nome }}</b></span>
        <br /><br />
        <div id="div_id_nome" class="form-group">
            <label for="id_nome" class="col-form-label  requiredField">
                Etapa<span class="asteriskField">*</span>
            </label>
            <div class="">
                <input type="text" name="nome" value="{{ etapa.nome }}" maxlength="200" id="id_nome" class="textinput textInput form-control" required disabled="" />
                <small id="hint_id_nome" class="form-text text-muted">Nome da etapa.</small>
            </div>
        </div>
        <div id="div_id_descricao" class="form-group">
            <label for="id_descricao" class="col-form-label ">
                Descrição da etapa
            </label>
            <div class="">
                <input type="text" name="descricao" value="{{ etapa.descricao }}" maxlength="200" id="id_descricao" class="textinput textInput form-control" disabled="" />
                <small id="hint_id_descricao" class="form-text text-muted">Descreve a função da etapa.</small>
            </div>
        </div>
        <div id="div_id_ordem" class="form-group">
            <label for="id_ordem" class="col-form-label  requiredField">
                Ordem<span class="asteriskField">*</span>
            </label>
            <div class="">
                <input type="number" name="ordem" value="{{ etapa.ordem }}" class="numberinput form-control" id="id_ordem" min="0" required disabled="" />
                <small id="hint_id_ordem" class="form-text text-muted">Define a posição/ordem da etapa.</small>
            </div>
        </div>
        <div id="div_id_distribuicao" class="form-group">
            <label for="id_distribuicao" class="col-form-label ">Distribuição</label>
            <div class="">
                <select name="distribuicao" class="selectmultiple form-control" id="id_distribuicao" multiple disabled="" >
                {% for dist in etapa.distribuicao.all %}
                    <option value="{{ dist.id }}">{{ dist.nome }}</option>
                {% endfor %}
                </select>
                <small id="hint_id_distribuicao" class="form-text text-muted">Indica quais tipos de distribuição podem ser usados para essa etapa.</small>
            </div>
        </div>
        <div class="form-group">
            <div id="div_id_vincular_analista" class="form-check">
                <label for="id_vincular_analista" class="form-check-label">
                    <input type="checkbox" name="vincular_analista" class="checkboxinput form-check-input" id="id_vincular_analista" {% if etapa.vincular_analista %} checked="" {% endif %} disabled="" />
                    Vincular analista
                </label>
                <small id="hint_id_vincular_analista" class="form-text text-muted">Indica se o sistema deve se lembrar do usuário escolhido na primeira distribuição do processo.</small>
            </div>
        </div>
        <div class="form-group">
            <div id="div_id_is_active" class="form-check">
                <label for="id_is_active" class="form-check-label">
                    <input type="checkbox" name="is_active" class="checkboxinput form-check-input" id="id_is_active" {% if etapa.is_active %} checked="" {% endif %} disabled="" />
                    Está ativa?
                </label>
                <small id="hint_id_is_active" class="form-text text-muted">Indica se a etapa está ou não ativa.</small>
            </div>
        </div>


        <span class="text-muted float-right">
            <a href="{% url 'etapa_list' %}" class="btn btn-outline-secondary" rule="button">Voltar para lista</a>
            <a href="{% url 'etapa_edit' etapa.pk %}" class="btn btn-outline-primary" rule="button">Editar</a>
            <a href="{% url 'etapa_delete' etapa.pk %}" class="btn btn-outline-danger" rule="button">Apagar</a>
        </span>
        <br /><br /><br /><hr>
        <div>
            <a href="{% url 'acao_new'%}" rule="button" class="btn proj-btn-override btn-outline-success float-right">+ Novo</a>
            <h6>Ações cadastradas para esta etapa</h6>
            <br />
            <ul class="list-group">
            {% for acao in etapa.acao_set.all %}
                <li class="list-group-item justify-content-between">
                    <a href="{% url 'acao_detail' acao.pk %}">
                        {{ acao }}
                    </a>
                    <span class="text-muted float-right">
                        <a href="{% url 'acao_detail' acao.pk %}" class="btn proj-btn-override btn-outline-secondary" rule="button">Ver mais</a>
                        <a href="{% url 'acao_edit' acao.pk %}" class="btn proj-btn-override btn-outline-secondary" rule="button">Editar</a>
                        <a href="{% url 'acao_delete' acao.pk %}" class="btn proj-btn-override btn-outline-secondary" rule="button">Apagar</a>
                    </span>
                </li>
            {% endfor %}
            </ul>
        </div>
        <br /><br />
{% endblock content %}

templates/natureza_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Naturezas - Detalhes{% endblock title %}

{% block content %}
        <h3>Naturezas</h3>
        <span class="text-muted">Detalhes da natureza: <b>{{ natureza.nome }}</b></span>
        <br /><br />
        <div id="div_id_nome" class="form-group">
            <label for="id_nome" class="col-form-label  requiredField">
                Nome da Natureza<span class="asteriskField">*</span>
            </label>
            <div class="">
                <input type="text" name="nome" value="{{ natureza.nome }}" required id="id_nome" maxlength="200" class="textinput textInput form-control" disabled="" />
            </div>
        </div>
        <div id="div_id_prazo" class="form-group">
            <label for="id_prazo" class="col-form-label ">
                Prazo legal
            </label>
            <div class="">
                <input type="number" name="prazo" value="{{ natureza.prazo }}" id="id_prazo" class="numberinput form-control" disabled="" />
                <small id="hint_id_prazo" class="form-text text-muted">Prazo legal da prenotação. Período de validade oficial dos processos ligados à esta natureza.</small>
            </div>
        </div>
        <div class="form-group">
            <div id="div_id_is_active" class="form-check">
                <label for="id_is_active" class="form-check-label">
                    <input type="checkbox" name="is_active" id="id_is_active" class="checkboxinput form-check-input" {% if natureza.is_active %} checked="" {% endif %} disabled="" />
                    Está ativo?
                </label>
                <small id="hint_id_is_active" class="form-text text-muted">Indica se a natureza está ou não ativa.</small>
            </div>
        </div>


        <span class="text-muted float-right">
            <a href="{% url 'natureza_list' %}" class="btn btn-outline-secondary" rule="button">Voltar para lista</a>
            <a href="{% url 'natureza_edit' natureza.pk %}" class="btn btn-outline-primary" rule="button">Editar</a>
            <a href="{% url 'natureza_delete' natureza.pk %}" class="btn btn-outline-danger" rule="button">Apagar</a>
        </span>
        <br />
{% endblock content %}

templates/processo_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Processos - Detalhes{% endblock title %}

{% block content %}
        <h3>Processos</h3>
        <span class="text-muted">Detalhes da processo: <b>{{ processo.l1_protocolo }}</b></span>
        <br /><br />
        <div id="div_id_l1_protocolo" class="form-group">
            <label for="id_l1_protocolo" class="col-form-label  requiredField">
                Processo<span class="asteriskField">*</span>
            </label>
            <div class="">
                <input type="number" name="l1_protocolo" value="{{ processo.l1_protocolo }}" class="numberinput form-control" required id="id_l1_protocolo" disabled="" />
                <small id="hint_id_l1_protocolo" class="form-text text-muted">Número do processo/protocolo.</small>
            </div>
        </div>
        <div id="div_id_dta_inclusao" class="form-group">
            <label for="id_dta_inclusao" class="col-form-label  requiredField">Data de entrada<span class="asteriskField">*</span></label>
            <div class="">
                <input type="text" name="dta_inclusao" value="{{ processo.dta_inclusao }}" class="dateinput form-control" required disabled id="id_dta_inclusao">
                <small id="hint_id_dta_inclusao" class="form-text text-muted">Data em que o processo deu entrada (inclusão).</small>
            </div>
        </div>
        <div id="div_id_dta_prazo" class="form-group">
            <label for="id_dta_prazo" class="col-form-label  requiredField">Vencimento<span class="asteriskField">*</span> </label>
            <div class="">
                <input type="text" name="dta_prazo" value="{{ processo.dta_prazo }}" class="dateinput form-control" required disabled id="id_dta_prazo">
                <small id="hint_id_dta_prazo" class="form-text text-muted">Data em que vence o prazo legal do processo.</small>
            </div>
        </div>
        <div id="div_id_natureza" class="form-group">
            <label for="id_natureza" class="col-form-label  requiredField">
                Natureza<span class="asteriskField">*</span>
            </label>
            <div class="">
                <select name="natureza" class="select form-control" required id="id_natureza" disabled="">
                    <option value="">{{ processo.natureza }}</option>
                </select>
                <small id="hint_id_natureza" class="form-text text-muted">Natureza do processo.</small>
            </div>
        </div>
        <div id="div_id_etapa" class="form-group">
            <label for="id_etapa" class="col-form-label ">Etapa</label>
            <div class="">
                <select name="etapa" class="select form-control" id="id_etapa" disabled="">
                    <option value="" selected>{{ processo.etapa }}</option>
                </select>
                <small id="hint_id_etapa" class="form-text text-muted">Etapa do processo.</small>
            </div>
        </div>
        <div id="div_id_parte" class="form-group">
            <label for="id_parte" class="col-form-label ">Parte</label>
            <div class="">
                <input type="text" name="parte" value="{{ processo.parte }}" class="textinput textInput form-control" id="id_parte" maxlength="200" disabled="" />
                <small id="hint_id_parte" class="form-text text-muted">Nome/identificação da parte/cliente.</small>
            </div>
        </div>
        <div id="div_id_atendente" class="form-group">
            <label for="id_atendente" class="col-form-label  requiredField">Atendente<span class="asteriskField">*</span> </label>
            <div class="">
                <input type="text" name="atendente" value="{{ processo.atendente }}" class="textinput textInput form-control" required disabled id="id_atendente">
                <small id="hint_id_atendente" class="form-text text-muted">Nome/identificação do funcionário que deu entrada(incluiu) no processo.</small>
            </div>
        </div>
        <div id="div_id_agente" class="form-group">
            <label for="id_agente" class="col-form-label  requiredField">Agente<span class="asteriskField">*</span> </label>
            <div class="">
                <input type="text" name="agente" value="{{ processo.agente }}" class="textinput textInput form-control" required disabled id="id_agente">
                <small id="hint_id_agente" class="form-text text-muted">Nome/identificação do funcionário responsável pelo processo na presente etapa.</small>
            </div>
        </div>

        <span class="text-muted float-right">
            <a href="{% url 'processo_list' %}" class="btn btn-outline-secondary" rule="button">Voltar para lista</a>
            <a href="{% url 'processo_edit' processo.pk %}" class="btn btn-outline-primary" rule="button">Editar</a>
            <a href="{% url 'processo_delete' processo.pk %}" class="btn btn-outline-danger" rule="button">Apagar</a>
        </span>
        <br /><br />
{% endblock content %}

templates/processo_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Processos - Nova{% endblock title %}

{% block content %}
        <h3>Processos</h3>
        <span class="text-muted">Cadastrar processo</span>
        <br /><br />
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'processo_list' %}" class="btn btn-outline-secondary ml-2" rule="button">Voltar para lista</a>
            <input type="submit" class="btn btn-outline-success ml-2" value="Salvar">
        </form>

{% endblock content %}